package com.findupto.fastfood;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.print.PrinterJob;
import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/** Complete operational POS for MK Pizza & Ice Bar. */
public class CompletePOS extends JFrame {
    private static final String DB="jdbc:sqlite:fastfood.db", DEFAULT_CURRENCY="Rs.";
    private static final String BUSINESS="MK Pizza & Ice Bar", ADDRESS="Collage Road Abbas Chowk, Bhakkar, Pakistan", PHONE="0316 9700025";
    private static final DateTimeFormatter DT=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private final String user,role; private final List<Line> cart=new ArrayList<>();
    private final DefaultTableModel cm=model("Item","Qty","Price","Amount"); private final JTable ct=new JTable(cm);
    private final JLabel sub=new JLabel(),tax=new JLabel(),disc=new JLabel(),tot=new JLabel(),status=new JLabel(" Ready");
    private final JTextField discount=new JTextField("0",5),cash=new JTextField(8); private final JTextArea receipt=new JTextArea();
    record Product(int id,String code,String name,String cat,double price,int stock){} record Line(Product p,int qty){}
    public CompletePOS(String u,String r){user=u;role=r;setTitle(BUSINESS+" - POS");setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1280,820));setLocationRelativeTo(null);build();totals();}
    static DefaultTableModel model(String... x){return new DefaultTableModel(x,0){public boolean isCellEditable(int r,int c){return false;}};}
    static Connection db()throws SQLException{return DriverManager.getConnection(DB);}
    static String hash(String s){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes());StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}catch(Exception e){throw new RuntimeException(e);}}
    static void init(){try(Connection c=db();Statement s=c.createStatement()){
        s.execute("PRAGMA foreign_keys=ON");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE,password TEXT NOT NULL,role TEXT NOT NULL,active INTEGER DEFAULT 1)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT NOT NULL,category TEXT NOT NULL,price REAL NOT NULL,stock INTEGER DEFAULT 0,active INTEGER DEFAULT 1)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,receipt_no TEXT UNIQUE,sold_at TEXT,total REAL,discount REAL,tax REAL,cash REAL,change_amount REAL,payment TEXT,cashier TEXT,status TEXT DEFAULT 'COMPLETED')");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS sale_items(id INTEGER PRIMARY KEY AUTOINCREMENT,sale_id INTEGER REFERENCES sales(id),product_id INTEGER,product_name TEXT,qty INTEGER,price REAL,amount REAL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT,user TEXT,action TEXT,details TEXT)");
        set(c,"business_name",BUSINESS);set(c,"business_address",ADDRESS);set(c,"business_phone",PHONE);set(c,"currency",DEFAULT_CURRENCY);set(c,"tax_rate","0");set(c,"printer_bluetooth_mac","");set(c,"receipt_footer","Thank you! Visit again.");
        user(c,"admin","0099","ADMIN");user(c,"owner","0099","OWNER");
        Object[][] p={{"B01","Zinger Burger","Burgers",450,50},{"B02","Chicken Burger","Burgers",380,50},{"B03","Beef Burger","Burgers",520,30},{"F01","Chicken Fries","Fries",300,60},{"F02","Loaded Fries","Fries",420,40},{"P01","Chicken Pizza","Pizza",850,25},{"P02","Pepperoni Pizza","Pizza",950,25},{"D01","Cold Drink","Drinks",120,100},{"D02","Fresh Lemonade","Drinks",180,80},{"D03","Mineral Water","Drinks",80,100}};
        try(PreparedStatement q=c.prepareStatement("INSERT OR IGNORE INTO products(code,name,category,price,stock) VALUES(?,?,?,?,?)")){for(Object[] a:p){for(int i=0;i<a.length;i++)q.setObject(i+1,a[i]);q.addBatch();}q.executeBatch();}
    }catch(SQLException e){throw new RuntimeException(e);}}
    static void user(Connection c,String u,String p,String r)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT INTO users(username,password,role,active) VALUES(?,?,?,1) ON CONFLICT(username) DO UPDATE SET password=excluded.password,role=excluded.role,active=1")){q.setString(1,u);q.setString(2,hash(p));q.setString(3,r);q.executeUpdate();}}
    static void set(Connection c,String k,String v)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)")){q.setString(1,k);q.setString(2,v);q.executeUpdate();}}
    static String setting(String k,String d){try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT value FROM settings WHERE key=?")){q.setString(1,k);try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):d;}}catch(SQLException e){return d;}}
    static boolean login(String u,String p){try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT role FROM users WHERE username=? AND password=? AND active=1")){q.setString(1,u);q.setString(2,hash(p));q.setString(3,"");}catch(Exception ignored){}try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT role FROM users WHERE username=? AND password=? AND active=1")){q.setString(1,u);q.setString(2,hash(p));try(ResultSet r=q.executeQuery()){return r.next();}}catch(SQLException e){return false;}}
    static String role(String u){try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT role FROM users WHERE username=?")){q.setString(1,u);try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):"";}}catch(SQLException e){return "";}}
    static List<Product> products(){List<Product> z=new ArrayList<>();try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT id,code,name,category,price,stock FROM products WHERE active=1 ORDER BY category,name");ResultSet r=q.executeQuery()){while(r.next())z.add(new Product(r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getDouble(5),r.getInt(6)));}catch(SQLException e){warn(e.getMessage());}return z;}
    static double taxRate(){try{return Math.max(0,Double.parseDouble(setting("tax_rate","0")))/100;}catch(Exception e){return 0;}}
    static String money(double x){return setting("currency",DEFAULT_CURRENCY)+" "+String.format(Locale.US,"%,.2f",x);}
    void build(){JPanel root=new JPanel(new BorderLayout(8,8));root.setBorder(new EmptyBorder(10,10,10,10));JLabel t=new JLabel(setting("business_name",BUSINESS));t.setFont(new Font("SansSerif",Font.BOLD,26));JPanel h=new JPanel(new BorderLayout());h.add(t,BorderLayout.WEST);h.add(new JLabel("User: "+user+" | "+role),BorderLayout.EAST);root.add(h,BorderLayout.NORTH);JTabbedPane tabs=new JTabbedPane();tabs.addTab("POS",pos());tabs.addTab("Products / Stock",products());tabs.addTab("Sales History",history());tabs.addTab("Reports",reports());if(role.equals("ADMIN")||role.equals("OWNER")){tabs.addTab("Users",users());tabs.addTab("Settings",settings());tabs.addTab("Backup",backup());}root.add(tabs,BorderLayout.CENTER);status.setBorder(BorderFactory.createEtchedBorder());root.add(status,BorderLayout.SOUTH);setContentPane(root);}
    JPanel pos(){JPanel p=new JPanel(new BorderLayout(8,8));JPanel menu=new JPanel(new GridLayout(0,4,5,5));for(Product x:products()){JButton b=new JButton("<html><b>"+x.name()+"</b><br>"+money(x.price())+"<br>Stock "+x.stock()+"</html>");b.setEnabled(x.stock()>0);b.addActionListener(e->add(x));menu.add(b);}p.add(new JScrollPane(menu),BorderLayout.CENTER);JPanel r=new JPanel(new BorderLayout(5,5));r.setPreferredSize(new Dimension(510,650));r.add(new JScrollPane(ct),BorderLayout.CENTER);ct.setRowHeight(28);JPanel f=new JPanel(new GridLayout(0,2,5,5));f.add(new JLabel("Discount %"));f.add(discount);f.add(new JLabel("Cash"));f.add(cash);f.add(new JLabel("Subtotal"));f.add(sub);f.add(new JLabel("Tax"));f.add(tax);f.add(new JLabel("Discount"));f.add(disc);f.add(new JLabel("TOTAL"));f.add(tot);JButton rm=new JButton("Remove");rm.addActionListener(e->{int i=ct.getSelectedRow();if(i>=0){cart.remove(i);refresh();}});JButton qty=new JButton("Set Qty");qty.addActionListener(e->setQty());JButton clear=new JButton("Clear");clear.addActionListener(e->{cart.clear();refresh();});JButton co=new JButton("CHECKOUT");co.addActionListener(e->checkout());JButton pr=new JButton("Print");pr.addActionListener(e->print());JPanel a=new JPanel(newGrid(5));a.add(rm);a.add(qty);a.add(clear);a.add(pr);a.add(co);f.add(a);f.add(new JLabel());r.add(f,BorderLayout.SOUTH);p.add(r,BorderLayout.EAST);return p;}
    GridLayout newGrid(int n){return new GridLayout(1,n,4,4);}
    void add(Product p){for(Line l:cart)if(l.p.id()==p.id()){if(l.qty>=p.stock){warn("Not enough stock");return;}cart.set(cart.indexOf(l),new Line(l.p,l.qty+1));refresh();return;}cart.add(new Line(p,1));refresh();}
    void setQty(){int i=ct.getSelectedRow();if(i<0)return;String s=JOptionPane.showInputDialog(this,"Quantity:",cart.get(i).qty);try{int n=Integer.parseInt(s);if(n<1||n>cart.get(i).p.stock)throw new Exception();cart.set(i,new Line(cart.get(i).p,n));refresh();}catch(Exception e){warn("Invalid quantity");}}
    void refresh(){cm.setRowCount(0);for(Line l:cart)cm.addRow(new Object[]{l.p.name,l.qty,money(l.p.price),money(l.p.price*l.qty)});totals();}
    double subtotal(){return cart.stream().mapToDouble(x->x.p.price*x.qty).sum();}double discountAmount(){try{return Math.min(100,Math.max(0,Double.parseDouble(discount.getText())))*subtotal()/100;}catch(Exception e){return 0;}}double taxAmount(){return (subtotal()-discountAmount())*taxRate();}double total(){return subtotal()-discountAmount()+taxAmount();}
    void totals(){sub.setText(money(subtotal()));tax.setText(money(taxAmount()));disc.setText(money(discountAmount()));tot.setText(money(total()));tot.setFont(tot.getFont().deriveFont(Font.BOLD,16f));}
    void checkout(){if(cart.isEmpty()){warn("Order is empty");return;}double cashValue;try{cashValue=Double.parseDouble(cash.getText());}catch(Exception e){warn("Enter valid cash");return;}if(cashValue<total()){warn("Insufficient cash. Required "+money(total()));return;}String no="MK-"+System.currentTimeMillis();double change=cashValue-total();try(Connection c=db()){c.setAutoCommit(false);try(PreparedStatement s=c.prepareStatement("INSERT INTO sales(receipt_no,sold_at,total,discount,tax,cash,change_amount,payment,cashier,status) VALUES(?,?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){s.setString(1,no);s.setString(2,LocalDateTime.now().format(DT));s.setDouble(3,total());s.setDouble(4,discountAmount());s.setDouble(5,taxAmount());s.setDouble(6,cashValue);s.setDouble(7,change);s.setString(8,"CASH");s.setString(9,user);s.setString(10,"COMPLETED");s.executeUpdate();int id;try(ResultSet k=s.getGeneratedKeys()){k.next();id=k.getInt(1);}try(PreparedStatement i=c.prepareStatement("INSERT INTO sale_items(sale_id,product_id,product_name,qty,price,amount) VALUES(?,?,?,?,?,?)");PreparedStatement u=c.prepareStatement("UPDATE products SET stock=stock-? WHERE id=? AND stock>=?")){for(Line l:cart){u.setInt(1,l.qty);u.setInt(2,l.p.id);u.setInt(3,l.qty);if(u.executeUpdate()!=1)throw new SQLException("Stock changed: "+l.p.name);i.setInt(1,id);i.setInt(2,l.p.id);i.setString(3,l.p.name);i.setInt(4,l.qty);i.setDouble(5,l.p.price);i.setDouble(6,l.p.price*l.qty);i.addBatch();}i.executeBatch();}audit(c,"SALE","Receipt "+no);c.commit();}}catch(Exception e){warn("Checkout failed: "+e.getMessage());return;}receipt.setText(receipt(no,cashValue,change));cart.clear();cash.setText("");discount.setText("0");refresh();status.setText(" Sale "+no+" saved");JOptionPane.showMessageDialog(this,"Sale completed: "+no);}
    String receipt(String no,double cashValue,double change){StringBuilder b=new StringBuilder();b.append("========================================\n").append(setting("business_name",BUSINESS)).append("\n").append(setting("business_address",ADDRESS)).append("\nPhone: ").append(setting("business_phone",PHONE)).append("\nReceipt: ").append(no).append("\n").append(LocalDateTime.now().format(DT)).append("\nCashier: ").append(user).append("\n========================================\n");for(Line l:cart)b.append(String.format("%-23s %2dx %12s%n",l.p.name,l.qty,money(l.p.price*l.qty)));b.append("----------------------------------------\n");b.append(String.format("%-25s %12s%n","Subtotal",money(subtotal())));b.append(String.format("%-25s %12s%n","Discount",money(discountAmount())));b.append(String.format("%-25s %12s%n","Tax",money(taxAmount())));b.append(String.format("%-25s %12s%n","TOTAL",money(total())));b.append(String.format("%-25s %12s%n","Cash",money(cashValue)));b.append(String.format("%-25s %12s%n","Change",money(change)));b.append("========================================\n").append(setting("receipt_footer","Thank you! Visit again.")).append("\n");return b.toString();}
    JPanel products(){DefaultTableModel m=model("ID","Code","Name","Category","Price","Stock");JTable t=new JTable(m);reloadProducts(m);JTextField code=new JTextField(6),name=new JTextField(14),cat=new JTextField(10),price=new JTextField(7),stock=new JTextField(5);JPanel f=new JPanel(new FlowLayout());for(Component x:new Component[]{new JLabel("Code"),code,new JLabel("Name"),name,new JLabel("Category"),cat,new JLabel("Price"),price,new JLabel("Stock"),stock})f.add(x);JButton save=new JButton("Save");save.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO products(code,name,category,price,stock,active) VALUES(?,?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,category=excluded.category,price=excluded.price,stock=excluded.stock,active=1")){q.setString(1,code.getText().trim());q.setString(2,name.getText().trim());q.setString(3,cat.getText().trim());q.setDouble(4,Double.parseDouble(price.getText()));q.setInt(5,Integer.parseInt(stock.getText()));q.executeUpdate();reloadProducts(m);}catch(Exception x){warn(x.getMessage());}});JButton off=new JButton("Deactivate");off.addActionListener(e->{int i=t.getSelectedRow();if(i>=0)try(Connection c=db();PreparedStatement q=c.prepareStatement("UPDATE products SET active=0 WHERE id=?")){q.setInt(1,(int)m.getValueAt(i,0));q.executeUpdate();reloadProducts(m);}catch(SQLException x){warn(x.getMessage());}});f.add(save);f.add(off);JPanel p=new JPanel(new BorderLayout());p.add(new JScrollPane(t));p.add(f,BorderLayout.SOUTH);return p;}
    void reloadProducts(DefaultTableModel m){m.setRowCount(0);for(Product p:products())m.addRow(new Object[]{p.id,p.code,p.name,p.cat,money(p.price),p.stock});}
    JPanel history(){DefaultTableModel m=model("ID","Receipt","Date","Total","Cashier","Payment","Status");JTable t=new JTable(m);JTextField search=new JTextField(18);JButton load=new JButton("Search / Refresh");load.addActionListener(e->loadHistory(m,search.getText()));loadHistory(m,"");JButton refund=new JButton("Refund Selected");refund.setEnabled(role.equals("ADMIN")||role.equals("OWNER"));refund.addActionListener(e->{int r=t.getSelectedRow();if(r>=0)refund((int)m.getValueAt(r,0),m);});JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT));top.add(new JLabel("Receipt:"));top.add(search);top.add(load);top.add(refund);JPanel p=new JPanel(new BorderLayout());p.add(top,BorderLayout.NORTH);p.add(new JScrollPane(t));return p;}
    void loadHistory(DefaultTableModel m,String term){m.setRowCount(0);String q="SELECT id,receipt_no,sold_at,total,cashier,payment,status FROM sales WHERE receipt_no LIKE ? ORDER BY id DESC LIMIT 200";try(Connection c=db();PreparedStatement s=c.prepareStatement(q)){s.setString(1,"%"+term+"%");try(ResultSet r=s.executeQuery()){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),money(r.getDouble(4)),r.getString(5),r.getString(6),r.getString(7)});}}catch(SQLException e){warn(e.getMessage());}}
    void refund(int id,DefaultTableModel m){if(JOptionPane.showConfirmDialog(this,"Refund this entire sale and return stock?","Confirm",JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_OPTION)return;try(Connection c=db()){c.setAutoCommit(false);try(PreparedStatement q=c.prepareStatement("SELECT status FROM sales WHERE id=?")){q.setInt(1,id);try(ResultSet r=q.executeQuery()){if(!r.next()||!r.getString(1).equals("COMPLETED"))throw new SQLException("Sale already refunded");}}try(PreparedStatement i=c.prepareStatement("SELECT product_id,qty FROM sale_items WHERE sale_id=?");PreparedStatement u=c.prepareStatement("UPDATE products SET stock=stock+? WHERE id=?")){i.setInt(1,id);try(ResultSet r=i.executeQuery()){while(r.next()){u.setInt(1,r.getInt(2));u.setInt(2,r.getInt(1));u.executeUpdate();}}}try(PreparedStatement s=c.prepareStatement("UPDATE sales SET status='REFUNDED' WHERE id=?")){s.setInt(1,id);s.executeUpdate();}audit(c,"REFUND","Sale ID "+id);c.commit();loadHistory(m,"");}catch(Exception e){try{c.rollback();}catch(Exception ignored){}warn(e.getMessage());}}
    JPanel reports(){JTextArea out=new JTextArea();out.setEditable(false);out.setFont(new Font(Font.MONOSPACED,Font.PLAIN,13));JButton b=new JButton("Refresh");b.addActionListener(e->out.setText(report()));out.setText(report());JPanel p=new JPanel(new BorderLayout());p.add(b,BorderLayout.NORTH);p.add(new JScrollPane(out));return p;}
    String report(){StringBuilder b=new StringBuilder(setting("business_name",BUSINESS)+"\nDASHBOARD\n====================\n");try(Connection c=db();Statement s=c.createStatement()){try(ResultSet r=s.executeQuery("SELECT COUNT(*),COALESCE(SUM(total),0),COALESCE(AVG(total),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')")){r.next();b.append("Today Orders: ").append(r.getInt(1)).append("\nToday Sales : ").append(money(r.getDouble(2))).append("\nAvg Order   : ").append(money(r.getDouble(3))).append("\n\n");}b.append("TOP ITEMS\n");try(ResultSet r=s.executeQuery("SELECT product_name,SUM(qty) FROM sale_items JOIN sales ON sales.id=sale_items.sale_id WHERE sales.status='COMPLETED' GROUP BY product_name ORDER BY SUM(qty) DESC LIMIT 10")){while(r.next())b.append(String.format("%-30s %5d%n",r.getString(1),r.getInt(2)));}b.append("\nLOW STOCK <=10\n");try(ResultSet r=s.executeQuery("SELECT code,name,stock FROM products WHERE active=1 AND stock<=10 ORDER BY stock")){while(r.next())b.append(String.format("%-7s %-28s %5d%n",r.getString(1),r.getString(2),r.getInt(3)));}}catch(SQLException e){b.append(e.getMessage());}return b.toString();}
    JPanel users(){DefaultTableModel m=model("ID","Username","Role","Active");JTable t=new JTable(m);loadUsers(m);JTextField u=new JTextField(10),p=new JTextField(10);JComboBox<String> r=new JComboBox<>(new String[]{"ADMIN","OWNER"});JPanel f=new JPanel();f.add(new JLabel("User"));f.add(u);f.add(new JLabel("Password"));f.add(p);f.add(r);JButton save=new JButton("Save User");save.addActionListener(e->{try(Connection c=db()){user(c,u.getText().trim(),p.getText(),(String)r.getSelectedItem());loadUsers(m);}catch(Exception x){warn(x.getMessage());}});JButton off=new JButton("Disable");off.addActionListener(e->{int i=t.getSelectedRow();if(i>=0)try(Connection c=db();PreparedStatement q=c.prepareStatement("UPDATE users SET active=0 WHERE id=?")){q.setInt(1,(int)m.getValueAt(i,0));q.executeUpdate();loadUsers(m);}catch(SQLException x){warn(x.getMessage());}});f.add(save);f.add(off);JPanel x=new JPanel(new BorderLayout());x.add(new JScrollPane(t));x.add(f,BorderLayout.SOUTH);return x;}
    void loadUsers(DefaultTableModel m){m.setRowCount(0);try(Connection c=db();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT id,username,role,active FROM users ORDER BY username")){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),r.getInt(4)==1});}catch(SQLException e){warn(e.getMessage());}}
    JPanel settings(){JTextField[] f={new JTextField(setting("business_name",BUSINESS),25),new JTextField(setting("business_address",ADDRESS),25),new JTextField(setting("business_phone",PHONE),18),new JTextField(setting("currency",DEFAULT_CURRENCY),8),new JTextField(setting("tax_rate","0"),8),new JTextField(setting("printer_bluetooth_mac",""),20),new JTextField(setting("receipt_footer","Thank you! Visit again."),25)};String[] n={"Business","Address","Phone","Currency","Tax %","Bluetooth MAC","Receipt Footer"};JPanel p=new JPanel(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(6,6,6,6);for(int i=0;i<n.length;i++){g.gridx=0;g.gridy=i;p.add(new JLabel(n[i]),g);g.gridx=1;p.add(f[i],g);}JButton s=new JButton("Save Settings");s.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value")){String[] k={"business_name","business_address","business_phone","currency","tax_rate","printer_bluetooth_mac","receipt_footer"};for(int i=0;i<k.length;i++){q.setString(1,k[i]);q.setString(2,f[i].getText().trim());q.addBatch();}q.executeBatch();status.setText(" Settings saved");}catch(SQLException x){warn(x.getMessage());}});g.gridx=1;g.gridy=n.length;p.add(s,g);return p;}
    JPanel backup(){JPanel p=new JPanel(new FlowLayout(FlowLayout.LEFT));JButton b=new JButton("Backup Database");b.addActionListener(e->{JFileChooser fc=new JFileChooser();fc.setSelectedFile(new File("fastfood-backup-"+System.currentTimeMillis()+".db"));if(fc.showSaveDialog(this)==JFileChooser.APPROVE_OPTION)try{Files.copy(Path.of("fastfood.db"),fc.getSelectedFile().toPath(),StandardCopyOption.REPLACE_EXISTING);status.setText(" Backup created");}catch(IOException x){warn(x.getMessage());}});p.add(b);p.add(new JLabel("Copy the backup to a safe location. Restore only when the POS is closed."));return p;}
    void audit(Connection c,String a,String d)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT INTO audit_log(at,user,action,details) VALUES(?,?,?,?)")){q.setString(1,LocalDateTime.now().format(DT));q.setString(2,user);q.setString(3,a);q.setString(4,d);q.executeUpdate();}}
    void print(){if(receipt.getText().isBlank()){warn("Complete a sale first");return;}try{PrinterJob j=PrinterJob.getPrinterJob();j.setPrintable((g,p,i)->{if(i>0)return java.awt.print.Printable.NO_SUCH_PAGE;g.setFont(new Font(Font.MONOSPACED,Font.PLAIN,9));int y=35;for(String x:receipt.getText().split("\\n")){g.drawString(x,25,y);y+=12;}return java.awt.print.Printable.PAGE_EXISTS;});if(j.printDialog())j.print();}catch(Exception e){warn(e.getMessage());}}
    static void warn(String x){JOptionPane.showMessageDialog(null,x,"POS",JOptionPane.WARNING_MESSAGE);}
    public static void main(String[] a){init();SwingUtilities.invokeLater(()->{try{UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}catch(Exception ignored){}JTextField u=new JTextField("admin"),p=new JPasswordField();JPanel x=new JPanel(new GridLayout(2,2,6,6));x.add(new JLabel("Username"));x.add(u);x.add(new JLabel("Password"));x.add(p);while(true){if(JOptionPane.showConfirmDialog(null,x,"MK Pizza & Ice Bar Login",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)System.exit(0);if(login(u.getText().trim(),new String(((JPasswordField)p).getPassword()))){new CompletePOS(u.getText().trim(),role(u.getText().trim())).setVisible(true);break;}warn("Invalid username or password");((JPasswordField)p).setText("");}});}
}