package com.findupto.fastfood;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.sql.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Enterprise management shell for MK Pizza & Ice Bar.
 * Adds operational modules on top of the existing SQLite POS database.
 */
public final class EnterprisePOS extends JFrame {
    static final String DB="jdbc:sqlite:fastfood.db";
    static final DateTimeFormatter DT=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    final String user, role; final JTabbedPane tabs=new JTabbedPane();
    EnterprisePOS(String u,String r){user=u;role=r; setTitle("MK Pizza & Ice Bar - Management"); setDefaultCloseOperation(EXIT_ON_CLOSE); setMinimumSize(new Dimension(1280,800)); setLocationRelativeTo(null); migrate(); build();}
    static Connection db() throws SQLException { Connection c=DriverManager.getConnection(DB); try(Statement s=c.createStatement()){s.execute("PRAGMA foreign_keys=ON");} return c; }
    static void exec(Connection c,String sql)throws SQLException{try(Statement s=c.createStatement()){s.executeUpdate(sql);}}
    static String q(Connection c,String sql,String d)throws SQLException{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){return r.next()?r.getString(1):d;}}
    static void set(Connection c,String k,String v)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value")){p.setString(1,k);p.setString(2,v);p.executeUpdate();}}
    void migrate(){try(Connection c=db()){
        exec(c,"CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,active INTEGER DEFAULT 1)");
        exec(c,"CREATE TABLE IF NOT EXISTS product_images(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,path TEXT NOT NULL)");
        exec(c,"CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");
        exec(c,"CREATE TABLE IF NOT EXISTS customer_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER REFERENCES customers(id),at TEXT NOT NULL,type TEXT NOT NULL,ref TEXT,amount REAL NOT NULL,note TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,email TEXT,address TEXT,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");
        exec(c,"CREATE TABLE IF NOT EXISTS supplier_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,supplier_id INTEGER REFERENCES suppliers(id),at TEXT NOT NULL,type TEXT NOT NULL,ref TEXT,amount REAL NOT NULL,note TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT NOT NULL,category TEXT,amount REAL NOT NULL,note TEXT,user TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS cash_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,business_date TEXT UNIQUE NOT NULL,opened_at TEXT,opening_cash REAL DEFAULT 0,closing_cash REAL,closed_at TEXT,status TEXT DEFAULT 'OPEN',user TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS cash_transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT NOT NULL,type TEXT NOT NULL,amount REAL NOT NULL,note TEXT,user TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,at TEXT NOT NULL,type TEXT NOT NULL,qty INTEGER,cost REAL,note TEXT,user TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS purchase_headers(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT NOT NULL,supplier_id INTEGER,total REAL,paid REAL,status TEXT,user TEXT)");
        exec(c,"CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_id INTEGER,product_id INTEGER,qty INTEGER,cost REAL,amount REAL)");
        exec(c,"CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL)");
        set(c,"business_day_start",get(c,"business_day_start","06:00")); set(c,"printer_width","80mm"); set(c,"printer_auto_reconnect","true");
        exec(c,"INSERT OR IGNORE INTO categories(name) SELECT DISTINCT category FROM products WHERE category IS NOT NULL AND category<>''");
    }catch(SQLException e){throw new RuntimeException("Enterprise migration failed: "+e.getMessage(),e);}}
    static String get(Connection c,String k,String d)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT value FROM settings WHERE key=?")){p.setString(1,k);try(ResultSet r=p.executeQuery()){return r.next()?r.getString(1):d;}}}
    static String now(){return LocalDateTime.now().format(DT);} static String money(double n){return String.format(Locale.US,"Rs. %,.2f",n);}
    static DefaultTableModel model(String... h){return new DefaultTableModel(h,0){public boolean isCellEditable(int r,int c){return false;}};}
    void build(){
        JPanel root=new JPanel(new BorderLayout(8,8)); JLabel head=new JLabel("MK Pizza & Ice Bar | "+user+" | "+role); head.setFont(head.getFont().deriveFont(Font.BOLD,20f)); root.add(head,BorderLayout.NORTH);
        tabs.addTab("Dashboard",dashboard()); tabs.addTab("Products / Menu",products()); tabs.addTab("Customers",people(true)); tabs.addTab("Suppliers",people(false)); tabs.addTab("Expenses",expenses()); tabs.addTab("Cash & Business Day",cash()); tabs.addTab("Reports / Profit",reports()); tabs.addTab("Printer",printer()); if(role.equals("ADMIN")||role.equals("OWNER")) tabs.addTab("Settings",settings()); root.add(tabs); setContentPane(root);
    }
    JPanel dashboard(){JPanel p=new JPanel(new BorderLayout(8,8)); JTextArea a=new JTextArea(); a.setEditable(false); JButton r=new JButton("Refresh"); r.addActionListener(e->dashboardText(a)); p.add(r,BorderLayout.NORTH); p.add(new JScrollPane(a)); dashboardText(a); return p;}
    void dashboardText(JTextArea a){try(Connection c=db()){double sales=num(c,"SELECT COALESCE(SUM(total),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')");double exp=num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(at)=date('now','localtime')");double dues=num(c,"SELECT COALESCE(SUM(opening_balance),0) FROM customers WHERE active=1");a.setText("TODAY\nSales: "+money(sales)+"\nExpenses: "+money(exp)+"\nCustomer opening balances: "+money(dues)+"\n\nUse the modules above for detailed ledgers, stock, cash and reports.");}catch(SQLException e){a.setText(e.getMessage());}}
    static double num(Connection c,String sql)throws SQLException{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){return r.next()?r.getDouble(1):0;}}
    JPanel products(){JPanel p=new JPanel(new BorderLayout(6,6)); DefaultTableModel m=model("ID","Code","Name","Category","Cost","Price","Stock","Image"); JTable t=new JTable(m); loadProducts(m); p.add(new JScrollPane(t));
        JPanel f=new JPanel(new FlowLayout()); JTextField code=new JTextField(6),name=new JTextField(14),cat=new JTextField(10),cost=new JTextField(7),price=new JTextField(7),stock=new JTextField(6),img=new JTextField(14);
        for(Component x:new Component[]{new JLabel("Code"),code,new JLabel("Name"),name,new JLabel("Category"),cat,new JLabel("Cost"),cost,new JLabel("Price"),price,new JLabel("Stock"),stock,new JLabel("Image"),img})f.add(x);
        JButton save=new JButton("Save/Edit"); save.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO products(code,name,category,cost_price,price,stock,active) VALUES(?,?,?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,category=excluded.category,cost_price=excluded.cost_price,price=excluded.price,stock=excluded.stock,active=1")){q.setString(1,code.getText().trim());q.setString(2,name.getText().trim());q.setString(3,cat.getText().trim());q.setDouble(4,Double.parseDouble(cost.getText()));q.setDouble(5,Double.parseDouble(price.getText()));q.setInt(6,Integer.parseInt(stock.getText()));q.executeUpdate();saveImage(c,code.getText().trim(),img.getText().trim());loadProducts(m);}catch(Exception x){JOptionPane.showMessageDialog(this,x.getMessage());}});
        JButton deactivate=new JButton("Delete/Deactivate"); deactivate.addActionListener(e->{int r=t.getSelectedRow();if(r<0)return;try(Connection c=db();PreparedStatement q=c.prepareStatement("UPDATE products SET active=0 WHERE id=?")){q.setInt(1,(Integer)m.getValueAt(r,0));q.executeUpdate();loadProducts(m);}catch(SQLException x){JOptionPane.showMessageDialog(this,x.getMessage());}});
        JButton bulkIn=new JButton("Import CSV"); bulkIn.addActionListener(e->bulkImport()); JButton bulkOut=new JButton("Export CSV"); bulkOut.addActionListener(e->bulkExport()); JButton images=new JButton("Bulk Images Folder"); images.addActionListener(e->bulkImages()); f.add(save);f.add(deactivate);f.add(bulkIn);f.add(bulkOut);f.add(images);p.add(f,BorderLayout.SOUTH);return p;}
    void loadProducts(DefaultTableModel m){m.setRowCount(0);try(Connection c=db();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT p.id,p.code,p.name,p.category,COALESCE(p.cost_price,0),p.price,p.stock,COALESCE((SELECT path FROM product_images i WHERE i.product_id=p.id ORDER BY i.id LIMIT 1),'') FROM products p WHERE p.active=1 ORDER BY p.category,p.name")){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),r.getString(4),money(r.getDouble(5)),money(r.getDouble(6)),r.getInt(7),r.getString(8)});}catch(SQLException e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    void saveImage(Connection c,String code,String path)throws SQLException{if(path.isBlank())return;try(PreparedStatement p=c.prepareStatement("INSERT INTO product_images(product_id,path) SELECT id,? FROM products WHERE code=?")){p.setString(1,path);p.setString(2,code);p.executeUpdate();}}
    void bulkImport(){JFileChooser fc=new JFileChooser();if(fc.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return;try{List<String> lines=Files.readAllLines(fc.getSelectedFile().toPath(),StandardCharsets.UTF_8);try(Connection c=db()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO products(code,name,category,cost_price,price,stock,active) VALUES(?,?,?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,category=excluded.category,cost_price=excluded.cost_price,price=excluded.price,stock=excluded.stock,active=1")){for(int i=1;i<lines.size();i++){String[] a=csv(lines.get(i));if(a.length<6)continue;p.setString(1,a[0]);p.setString(2,a[1]);p.setString(3,a[2]);p.setDouble(4,Double.parseDouble(a[3]));p.setDouble(5,Double.parseDouble(a[4]));p.setInt(6,Integer.parseInt(a[5]));p.addBatch();}p.executeBatch();c.commit();}}JOptionPane.showMessageDialog(this,"Bulk menu imported.");tabs.setComponentAt(1,products());}catch(Exception e){JOptionPane.showMessageDialog(this,"Import failed: "+e.getMessage());}}
    static String[] csv(String s){List<String> a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(char ch:s.toCharArray()){if(ch=='\"')q=!q;else if(ch==','&&!q){a.add(b.toString().trim());b.setLength(0);}else b.append(ch);}a.add(b.toString().trim());return a.toArray(String[]::new);}
    void bulkExport(){JFileChooser fc=new JFileChooser();fc.setSelectedFile(new File("menu.csv"));if(fc.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;try(Connection c=db();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT code,name,category,COALESCE(cost_price,0),price,stock FROM products ORDER BY code");BufferedWriter w=Files.newBufferedWriter(fc.getSelectedFile().toPath(),StandardCharsets.UTF_8)){w.write("code,name,category,cost_price,selling_price,stock,image\n");while(r.next())w.write(String.join(",",Arrays.asList(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),""))+"\n");}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    void bulkImages(){JFileChooser fc=new JFileChooser();fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);if(fc.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return;int n=0;try(Connection c=db()){for(Path f:Files.newDirectoryStream(fc.getSelectedFile().toPath())){String code=f.getFileName().toString().replaceFirst("\\.[^.]+$","");try(PreparedStatement p=c.prepareStatement("INSERT INTO product_images(product_id,path) SELECT id,? FROM products WHERE code=?")){p.setString(1,f.toAbsolutePath().toString());p.setString(2,code);n+=p.executeUpdate();}}}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}JOptionPane.showMessageDialog(this,"Linked "+n+" product images by filename/code.");}
    JPanel people(boolean customer){String table=customer?"customers":"suppliers", ledger=customer?"customer_ledger":"supplier_ledger";JPanel p=new JPanel(new BorderLayout(6,6));DefaultTableModel m=model("ID","Name","Phone","Email","Address","Opening","Ledger Balance");JTable t=new JTable(m);loadPeople(m,table,ledger);p.add(new JScrollPane(t));JPanel f=new JPanel(new FlowLayout());JTextField name=new JTextField(14),phone=new JTextField(10),email=new JTextField(12),addr=new JTextField(14),opening=new JTextField(8),amount=new JTextField(8),note=new JTextField(12);for(Component x:new Component[]{new JLabel("Name"),name,new JLabel("Phone"),phone,new JLabel("Email"),email,new JLabel("Address"),addr,new JLabel("Opening"),opening,new JLabel("Payment/Advance"),amount,new JLabel("Note"),note})f.add(x);
        JButton save=new JButton("Save");save.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO "+table+"(name,phone,email,address,opening_balance) VALUES(?,?,?,?,?)")){q.setString(1,name.getText());q.setString(2,phone.getText());q.setString(3,email.getText());q.setString(4,addr.getText());q.setDouble(5,Double.parseDouble(opening.getText().isBlank()?"0":opening.getText()));q.executeUpdate();loadPeople(m,table,ledger);}catch(Exception x){JOptionPane.showMessageDialog(this,x.getMessage());}});
        JButton pay=new JButton(customer?"Receive":"Pay Supplier");pay.addActionListener(e->{int r=t.getSelectedRow();if(r<0)return;try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO "+ledger+"("+(customer?"customer_id":"supplier_id")+",at,type,amount,note) VALUES(?,?,?,?,?)")){q.setInt(1,(Integer)m.getValueAt(r,0));q.setString(2,now());q.setString(3,customer?"PAYMENT_RECEIVED":"PAYMENT_MADE");q.setDouble(4,Double.parseDouble(amount.getText()));q.setString(5,note.getText());q.executeUpdate();loadPeople(m,table,ledger);}catch(Exception x){JOptionPane.showMessageDialog(this,x.getMessage());}});f.add(save);f.add(pay);p.add(f,BorderLayout.SOUTH);t.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&t.getSelectedRow()>=0)showLedger(table,ledger,(Integer)m.getValueAt(t.getSelectedRow(),0));});return p;}
    void loadPeople(DefaultTableModel m,String table,String ledger){m.setRowCount(0);try(Connection c=db();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT id,name,phone,email,address,opening_balance FROM "+table+" WHERE active=1 ORDER BY name")){while(r.next()){double bal=r.getDouble(6);int id=r.getInt(1);String idcol=table.equals("customers")?"customer_id":"supplier_id";bal+=num(c,"SELECT COALESCE(SUM(CASE WHEN type LIKE 'PAYMENT%' THEN -amount ELSE amount END),0) FROM "+ledger+" WHERE "+idcol+"="+id);m.addRow(new Object[]{id,r.getString(2),r.getString(3),r.getString(4),r.getString(5),money(r.getDouble(6)),money(bal)});}}catch(SQLException e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    void showLedger(String table,String ledger,int id){try(Connection c=db();PreparedStatement p=c.prepareStatement("SELECT at,type,amount,note FROM "+ledger+" WHERE "+(table.equals("customers")?"customer_id":"supplier_id")+"=? ORDER BY id DESC")){p.setInt(1,id);StringBuilder b=new StringBuilder("History\n");try(ResultSet r=p.executeQuery()){while(r.next())b.append(r.getString(1)).append(" | ").append(r.getString(2)).append(" | ").append(money(r.getDouble(3))).append(" | ").append(r.getString(4)).append('\n');}JOptionPane.showMessageDialog(this,new JScrollPane(new JTextArea(b.toString(),20,80)),"Ledger",JOptionPane.INFORMATION_MESSAGE);}catch(SQLException e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    JPanel expenses(){JPanel p=new JPanel(new BorderLayout());DefaultTableModel m=model("ID","Date","Category","Amount","Note","User");JTable t=new JTable(m);reloadExpenses(m);p.add(new JScrollPane(t));JPanel f=new JPanel(new FlowLayout());JTextField cat=new JTextField(12),amt=new JTextField(8),note=new JTextField(20);JButton add=new JButton("Add Expense");add.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO expenses(at,category,amount,note,user) VALUES(?,?,?,?,?)")){q.setString(1,now());q.setString(2,cat.getText());q.setDouble(3,Double.parseDouble(amt.getText()));q.setString(4,note.getText());q.setString(5,user);q.executeUpdate();reloadExpenses(m);}catch(Exception x){JOptionPane.showMessageDialog(this,x.getMessage());}});f.add(new JLabel("Category"));f.add(cat);f.add(new JLabel("Amount"));f.add(amt);f.add(note);f.add(add);p.add(f,BorderLayout.SOUTH);return p;}
    void reloadExpenses(DefaultTableModel m){m.setRowCount(0);try(Connection c=db();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT id,at,category,amount,note,user FROM expenses ORDER BY id DESC")){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),money(r.getDouble(4)),r.getString(5),r.getString(6)});}catch(SQLException e){}}
    JPanel cash(){JPanel p=new JPanel(new BorderLayout(8,8));JTextArea a=new JTextArea();a.setEditable(false);JPanel f=new JPanel(new FlowLayout());JTextField opening=new JTextField(10),amount=new JTextField(10),note=new JTextField(18);JButton open=new JButton("Open/Set Business Day");open.addActionListener(e->openDay(opening.getText()));JButton in=new JButton("Cash In");in.addActionListener(e->cashTx("CASH_IN",amount.getText(),note.getText()));JButton out=new JButton("Cash Out");out.addActionListener(e->cashTx("CASH_OUT",amount.getText(),note.getText()));JButton close=new JButton("Close & Reconcile");close.addActionListener(e->closeDay(a));f.add(new JLabel("Opening Cash"));f.add(opening);f.add(open);f.add(new JLabel("Amount"));f.add(amount);f.add(note);f.add(in);f.add(out);f.add(close);p.add(f,BorderLayout.NORTH);p.add(a);refreshCash(a);return p;}
    void openDay(String s){try{double x=Double.parseDouble(s);String d=businessDate();try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO cash_sessions(business_date,opened_at,opening_cash,status,user) VALUES(?,?,?,?,?) ON CONFLICT(business_date) DO UPDATE SET opening_cash=excluded.opening_cash,status='OPEN'")){q.setString(1,d);q.setString(2,now());q.setDouble(3,x);q.setString(4,"OPEN");q.setString(5,user);q.executeUpdate();}JOptionPane.showMessageDialog(this,"Business day opened: "+d);}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    String businessDate(){try{LocalTime t=LocalTime.parse(getSetting("business_day_start","06:00"));LocalDate d=LocalDate.now();if(LocalTime.now().isBefore(t))d=d.minusDays(1);return d.toString();}catch(Exception e){return LocalDate.now().toString();}}
    String getSetting(String k,String d){try(Connection c=db()){return get(c,k,d);}catch(Exception e){return d;}}
    void cashTx(String type,String s,String note){try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO cash_transactions(at,type,amount,note,user) VALUES(?,?,?,?,?)")){q.setString(1,now());q.setString(2,type);q.setDouble(3,Double.parseDouble(s));q.setString(4,note);q.setString(5,user);q.executeUpdate();}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    void refreshCash(JTextArea a){try(Connection c=db()){double sales=num(c,"SELECT COALESCE(SUM(cash),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')");double in=num(c,"SELECT COALESCE(SUM(amount),0) FROM cash_transactions WHERE type='CASH_IN' AND date(at)=date('now','localtime')");double out=num(c,"SELECT COALESCE(SUM(amount),0) FROM cash_transactions WHERE type='CASH_OUT' AND date(at)=date('now','localtime')");double exp=num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(at)=date('now','localtime')");a.setText("Business date: "+businessDate()+"\nSales cash: "+money(sales)+"\nCash in: "+money(in)+"\nCash out: "+money(out)+"\nExpenses: "+money(exp)+"\nExpected movement before change: "+money(sales+in-out-exp));}catch(SQLException e){a.setText(e.getMessage());}}
    void closeDay(JTextArea a){String actual=JOptionPane.showInputDialog(this,"Actual cash counted:");try{double x=Double.parseDouble(actual);double expected=0;try(Connection c=db()){expected=num(c,"SELECT COALESCE(SUM(cash-change_amount),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')")+num(c,"SELECT COALESCE(SUM(CASE WHEN type='CASH_IN' THEN amount ELSE -amount END),0) FROM cash_transactions WHERE date(at)=date('now','localtime')")-num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(at)=date('now','localtime')");try(PreparedStatement q=c.prepareStatement("UPDATE cash_sessions SET closing_cash=?,closed_at=?,status='CLOSED' WHERE business_date=?")){q.setDouble(1,x);q.setString(2,now());q.setString(3,businessDate());q.executeUpdate();}}a.setText("Expected cash: "+money(expected)+"\nActual cash: "+money(x)+"\nDifference: "+money(x-expected));}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    JPanel reports(){JPanel p=new JPanel(new BorderLayout(8,8));JTextArea a=new JTextArea();a.setEditable(false);JButton b=new JButton("Calculate P&L / Cash Flow");b.addActionListener(e->reportText(a));p.add(b,BorderLayout.NORTH);p.add(new JScrollPane(a));reportText(a);return p;}
    void reportText(JTextArea a){try(Connection c=db()){double sales=num(c,"SELECT COALESCE(SUM(total),0) FROM sales WHERE status='COMPLETED'");double refunds=num(c,"SELECT COALESCE(SUM(total),0) FROM sales WHERE status='REFUNDED'");double expenses=num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses");double revenue=sales-refunds;double cogs=num(c,"SELECT COALESCE(SUM(si.amount - (si.qty*COALESCE(p.cost_price,0))),0) FROM sale_items si LEFT JOIN products p ON p.id=si.product_id");double gross=revenue-cogs;double net=gross-expenses;a.setText("ALL-TIME FINANCIAL REPORT\n\nRevenue: "+money(revenue)+"\nCOGS: "+money(cogs)+"\nGross Profit: "+money(gross)+"\nExpenses: "+money(expenses)+"\nNET PROFIT / (LOSS): "+money(net)+"\n\nCash-flow transactions: "+money(num(c,"SELECT COALESCE(SUM(CASE WHEN type='CASH_IN' THEN amount ELSE -amount END),0) FROM cash_transactions")));}catch(SQLException e){a.setText(e.getMessage());}}
    JPanel printer(){JPanel p=new JPanel(new BorderLayout(8,8));JTextArea a=new JTextArea();a.setEditable(false);JTextField mac=new JTextField(getSetting("printer_bluetooth_mac",""),20);JButton save=new JButton("Save Printer MAC");save.addActionListener(e->{try(Connection c=db()){set(c,"printer_bluetooth_mac",mac.getText().trim());set(c,"printer_auto_reconnect","true");a.setText("Saved MAC: "+mac.getText()+"\nAuto-reconnect preference: enabled.\n\nDirect Bluetooth ESC/POS requires the OS Bluetooth stack/driver; this POS does not pretend a generic Java API can universally connect every printer.");}catch(Exception x){a.setText(x.getMessage());}});JButton detect=new JButton("Detect System Printers");detect.addActionListener(e->a.setText(PrinterService.detect()));JButton test=new JButton("Test 80mm Print");test.addActionListener(e->PrinterService.print("MK Pizza & Ice Bar\n80mm TEST RECEIPT\n"+now()+"\nThank you!\n"));JPanel f=new JPanel();f.add(new JLabel("Bluetooth MAC"));f.add(mac);f.add(save);f.add(detect);f.add(test);p.add(f,BorderLayout.NORTH);p.add(new JScrollPane(a));return p;}
    JPanel settings(){JPanel p=new JPanel(new GridLayout(0,2,8,8));String[] keys={"business_name","business_address","business_phone","currency","tax_rate","receipt_footer","business_day_start","printer_bluetooth_mac"};Map<String,JTextField> fields=new LinkedHashMap<>();for(String k:keys){p.add(new JLabel(k));JTextField f=new JTextField(getSetting(k,""));fields.put(k,f);p.add(f);}JButton save=new JButton("SAVE SETTINGS");save.addActionListener(e->{try(Connection c=db()){for(Map.Entry<String,JTextField>x:fields.entrySet())set(c,x.getKey(),x.getValue().getText());JOptionPane.showMessageDialog(this,"Settings saved. Restart POS if a module needs rebuilding.");}catch(Exception x){JOptionPane.showMessageDialog(this,x.getMessage());}});p.add(save);return p;}
    static final class PrinterService{static String detect(){StringBuilder b=new StringBuilder();try{String os=System.getProperty("os.name").toLowerCase();Process p;if(os.contains("win"))p=new ProcessBuilder("powershell","-NoProfile","-Command","Get-Printer | Select-Object Name,PrinterStatus | Out-String").start();else p=new ProcessBuilder("sh","-c","lpstat -p 2>/dev/null || lpstat -a 2>/dev/null").start();try(InputStream in=p.getInputStream()){b.append(new String(in.readAllBytes(),StandardCharsets.UTF_8));}p.waitFor();}catch(Exception e){b.append("Printer detection unavailable: ").append(e.getMessage());}return b.toString();}static void print(String text){try{JTextArea a=new JTextArea(text);a.print();}catch(Exception e){JOptionPane.showMessageDialog(null,"Print failed: "+e.getMessage());}}}
}
