package com.findupto.fastfood;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Font;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.sql.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Enterprise management modules for MK Pizza & Ice Bar. */
public final class EnterprisePOS extends JFrame {
    static final String DB="jdbc:sqlite:fastfood.db";
    static final DateTimeFormatter DT=DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    final String user,role; final JTabbedPane tabs=new JTabbedPane();
    EnterprisePOS(String u,String r){user=u;role=r;setTitle("MK Pizza & Ice Bar - POS");setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1280,800));setLocationRelativeTo(null);migrate();build();}
    static Connection db()throws SQLException{return DriverManager.getConnection(DB);}
    static DefaultTableModel model(String...h){return new DefaultTableModel(h,0){public boolean isCellEditable(int r,int c){return false;}};}
    static String now(){return LocalDateTime.now().format(DT);} static String money(double n){return String.format(Locale.US,"Rs. %,.2f",n);}
    static double num(Connection c,String sql)throws SQLException{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(sql)){return r.next()?r.getDouble(1):0;}}
    static String setting(Connection c,String k,String d)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT value FROM settings WHERE key=?")){p.setString(1,k);try(ResultSet r=p.executeQuery()){return r.next()?r.getString(1):d;}}}
    static void set(Connection c,String k,String v)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value")){p.setString(1,k);p.setString(2,v);p.executeUpdate();}}
    void migrate(){try(Connection c=db();Statement s=c.createStatement()){
        s.execute("CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)");
        s.execute("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,category TEXT,price REAL,stock INTEGER,active INTEGER DEFAULT 1)");
        if(!column(c,"products","cost_price"))s.execute("ALTER TABLE products ADD COLUMN cost_price REAL DEFAULT 0");
        s.execute("CREATE TABLE IF NOT EXISTS product_images(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,path TEXT NOT NULL)");
        s.execute("CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,email TEXT,address TEXT,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");
        s.execute("CREATE TABLE IF NOT EXISTS customer_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,at TEXT,type TEXT,amount REAL,note TEXT)");
        s.execute("CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,email TEXT,address TEXT,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1)");
        s.execute("CREATE TABLE IF NOT EXISTS supplier_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,supplier_id INTEGER,at TEXT,type TEXT,amount REAL,note TEXT)");
        s.execute("CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT,category TEXT,amount REAL,note TEXT,user TEXT)");
        s.execute("CREATE TABLE IF NOT EXISTS cash_sessions(id INTEGER PRIMARY KEY AUTOINCREMENT,business_date TEXT UNIQUE,opened_at TEXT,opening_cash REAL,closing_cash REAL,closed_at TEXT,status TEXT,user TEXT)");
        s.execute("CREATE TABLE IF NOT EXISTS cash_transactions(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT,type TEXT,amount REAL,note TEXT,user TEXT)");
        s.execute("CREATE TABLE IF NOT EXISTS stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER,at TEXT,type TEXT,qty INTEGER,cost REAL,note TEXT,user TEXT)");
        s.execute("CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,at TEXT,user TEXT,action TEXT,details TEXT)");
        setDefault(c,"business_name","MK Pizza & Ice Bar");setDefault(c,"business_address","Collage Road Abbas Chowk, Bhakkar, Pakistan");setDefault(c,"business_phone","0316 9700025");setDefault(c,"currency","Rs.");setDefault(c,"tax_rate","0");setDefault(c,"business_day_start","06:00");setDefault(c,"printer_bluetooth_mac","");setDefault(c,"printer_auto_reconnect","true");setDefault(c,"printer_width","80mm");setDefault(c,"receipt_footer","Thank you! Visit again.");
    }catch(SQLException e){throw new RuntimeException(e);}}
    static void setDefault(Connection c,String k,String v)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)")){p.setString(1,k);p.setString(2,v);p.executeUpdate();}}
    static boolean column(Connection c,String t,String n)throws SQLException{try(ResultSet r=c.createStatement().executeQuery("PRAGMA table_info("+t+")")){while(r.next())if(n.equalsIgnoreCase(r.getString("name")))return true;return false;}}
    void build(){JPanel root=new JPanel(new BorderLayout(8,8));JLabel h=new JLabel("MK Pizza & Ice Bar  |  "+user+" / "+role);h.setFont(h.getFont().deriveFont(Font.BOLD,21f));root.add(h,BorderLayout.NORTH);
        tabs.addTab("Dashboard",dashboard());tabs.addTab("Products / Menu",products());tabs.addTab("Customers",party(true));tabs.addTab("Suppliers",party(false));tabs.addTab("Expenses",expenses());tabs.addTab("Cash & Business Day",cash());tabs.addTab("Reports / P&L",reports());tabs.addTab("Printer",printer());if(role.equals("ADMIN")||role.equals("OWNER"))tabs.addTab("Settings",settings());root.add(tabs);setContentPane(root);}
    JPanel dashboard(){JPanel p=new JPanel(new BorderLayout());JTextArea a=new JTextArea();a.setEditable(false);JButton b=new JButton("Refresh");b.addActionListener(e->dashboardText(a));p.add(b,BorderLayout.NORTH);p.add(new JScrollPane(a));dashboardText(a);return p;}
    void dashboardText(JTextArea a){try(Connection c=db()){double s=num(c,"SELECT COALESCE(SUM(total),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')");double e=num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(at)=date('now','localtime')");double st=num(c,"SELECT COALESCE(SUM(stock*COALESCE(cost_price,0)),0) FROM products WHERE active=1");a.setText("TODAY\nSales: "+money(s)+"\nExpenses: "+money(e)+"\nStock cost value: "+money(st)+"\nBusiness date: "+businessDate()+"\n\nModules: Products, Customers, Suppliers, Expenses, Cash, Reports, Printer, Settings.");}catch(Exception e){a.setText(e.getMessage());}}
    JPanel products(){JPanel p=new JPanel(new BorderLayout(5,5));DefaultTableModel m=model("ID","Code","Name","Category","Cost","Price","Stock","Image");JTable t=new JTable(m);loadProducts(m);p.add(new JScrollPane(t));JPanel f=new JPanel(new FlowLayout());JTextField[] z={new JTextField(6),new JTextField(14),new JTextField(10),new JTextField(7),new JTextField(7),new JTextField(6),new JTextField(16)};String[] lab={"Code","Name","Category","Cost","Price","Stock","Image"};for(int i=0;i<z.length;i++){f.add(new JLabel(lab[i]));f.add(z[i]);}JButton save=new JButton("Save/Edit");save.addActionListener(e->saveProduct(z,m));JButton del=new JButton("Delete");del.addActionListener(e->{int r=t.getSelectedRow();if(r>=0)try(Connection c=db();PreparedStatement q=c.prepareStatement("UPDATE products SET active=0 WHERE id=?")){q.setInt(1,(Integer)m.getValueAt(r,0));q.executeUpdate();loadProducts(m);}catch(Exception x){err(x);}});JButton in=new JButton("Bulk Import CSV");in.addActionListener(e->bulkImport(m));JButton out=new JButton("Bulk Export CSV");out.addActionListener(e->bulkExport());JButton im=new JButton("Bulk Images");im.addActionListener(e->bulkImages());f.add(save);f.add(del);f.add(in);f.add(out);f.add(im);p.add(f,BorderLayout.SOUTH);t.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&t.getSelectedRow()>=0)productHistory((Integer)m.getValueAt(t.getSelectedRow(),0));});return p;}
    void loadProducts(DefaultTableModel m){m.setRowCount(0);try(Connection c=db();ResultSet r=c.createStatement().executeQuery("SELECT p.id,p.code,p.name,p.category,COALESCE(p.cost_price,0),p.price,p.stock,COALESCE((SELECT path FROM product_images i WHERE i.product_id=p.id ORDER BY i.id DESC LIMIT 1),'') FROM products p WHERE p.active=1 ORDER BY p.category,p.name")){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),r.getString(4),money(r.getDouble(5)),money(r.getDouble(6)),r.getInt(7),r.getString(8)});}catch(Exception e){err(e);}}
    void saveProduct(JTextField[] z,DefaultTableModel m){try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO products(code,name,category,cost_price,price,stock,active) VALUES(?,?,?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,category=excluded.category,cost_price=excluded.cost_price,price=excluded.price,stock=excluded.stock,active=1")){q.setString(1,z[0].getText());q.setString(2,z[1].getText());q.setString(3,z[2].getText());q.setDouble(4,Double.parseDouble(z[3].getText()));q.setDouble(5,Double.parseDouble(z[4].getText()));q.setInt(6,Integer.parseInt(z[5].getText()));q.executeUpdate();if(!z[6].getText().isBlank())try(PreparedStatement i=c.prepareStatement("INSERT INTO product_images(product_id,path) SELECT id,? FROM products WHERE code=?")){i.setString(1,z[6].getText());i.setString(2,z[0].getText());i.executeUpdate();}loadProducts(m);}catch(Exception e){err(e);}}
    void bulkImport(DefaultTableModel m){JFileChooser f=new JFileChooser();if(f.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return;try(Connection c=db();BufferedReader r=Files.newBufferedReader(f.getSelectedFile().toPath(),StandardCharsets.UTF_8);PreparedStatement q=c.prepareStatement("INSERT INTO products(code,name,category,cost_price,price,stock,active) VALUES(?,?,?,?,?,?,1) ON CONFLICT(code) DO UPDATE SET name=excluded.name,category=excluded.category,cost_price=excluded.cost_price,price=excluded.price,stock=excluded.stock,active=1")){String line;r.readLine();c.setAutoCommit(false);while((line=r.readLine())!=null){String[] a=csv(line);if(a.length<6)continue;q.setString(1,a[0]);q.setString(2,a[1]);q.setString(3,a[2]);q.setDouble(4,Double.parseDouble(a[3]));q.setDouble(5,Double.parseDouble(a[4]));q.setInt(6,Integer.parseInt(a[5]));q.addBatch();}q.executeBatch();c.commit();loadProducts(m);JOptionPane.showMessageDialog(this,"Menu imported.");}catch(Exception e){err(e);}}
    void bulkExport(){JFileChooser f=new JFileChooser();f.setSelectedFile(new File("menu.csv"));if(f.showSaveDialog(this)!=JFileChooser.APPROVE_OPTION)return;try(Connection c=db();ResultSet r=c.createStatement().executeQuery("SELECT code,name,category,COALESCE(cost_price,0),price,stock FROM products ORDER BY code");BufferedWriter w=Files.newBufferedWriter(f.getSelectedFile().toPath(),StandardCharsets.UTF_8)){w.write("code,name,category,cost_price,selling_price,stock,image\n");while(r.next())w.write(csvOut(r.getString(1))+","+csvOut(r.getString(2))+","+csvOut(r.getString(3))+","+r.getDouble(4)+","+r.getDouble(5)+","+r.getInt(6)+",\n");}catch(Exception e){err(e);}}
    void bulkImages(){JFileChooser f=new JFileChooser();f.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);if(f.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION)return;int n=0;try(Connection c=db();DirectoryStream<Path> ds=Files.newDirectoryStream(f.getSelectedFile().toPath())){for(Path x:ds){String code=x.getFileName().toString().replaceFirst("\\.[^.]+$","");try(PreparedStatement q=c.prepareStatement("INSERT INTO product_images(product_id,path) SELECT id,? FROM products WHERE code=?")){q.setString(1,x.toAbsolutePath().toString());q.setString(2,code);n+=q.executeUpdate();}}JOptionPane.showMessageDialog(this,"Linked "+n+" images by product code.");}catch(Exception e){err(e);}}
    static String[] csv(String s){List<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(char x:s.toCharArray()){if(x=='\"')q=!q;else if(x==','&&!q){a.add(b.toString().trim());b.setLength(0);}else b.append(x);}a.add(b.toString().trim());return a.toArray(String[]::new);}static String csvOut(String s){return "\""+s.replace("\"","\"\"")+"\"";}
    JPanel party(boolean customer){String table=customer?"customers":"suppliers",ledger=customer?"customer_ledger":"supplier_ledger",fk=customer?"customer_id":"supplier_id";JPanel p=new JPanel(new BorderLayout());DefaultTableModel m=model("ID","Name","Phone","Email","Address","Opening","Balance");JTable t=new JTable(m);loadParty(m,table,ledger,fk);p.add(new JScrollPane(t));JPanel f=new JPanel(new FlowLayout());JTextField n=new JTextField(12),ph=new JTextField(9),em=new JTextField(12),ad=new JTextField(12),op=new JTextField(7),amt=new JTextField(7),note=new JTextField(12);for(JTextField x:new JTextField[]{n,ph,em,ad,op,amt,note})f.add(x);f.add(new JLabel("Name Phone Email Address Opening Amount Note"));JButton add=new JButton("Add");add.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO "+table+"(name,phone,email,address,opening_balance) VALUES(?,?,?,?,?)")){q.setString(1,n.getText());q.setString(2,ph.getText());q.setString(3,em.getText());q.setString(4,ad.getText());q.setDouble(5,Double.parseDouble(op.getText().isBlank()?"0":op.getText()));q.executeUpdate();loadParty(m,table,ledger,fk);}catch(Exception x){err(x);}});JButton pay=new JButton(customer?"Receive Due/Advance":"Pay Supplier");pay.addActionListener(e->{int r=t.getSelectedRow();if(r<0)return;try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO "+ledger+"("+fk+",at,type,amount,note) VALUES(?,?,?,?,?)")){q.setInt(1,(Integer)m.getValueAt(r,0));q.setString(2,now());q.setString(3,customer?"PAYMENT_RECEIVED":"PAYMENT_MADE");q.setDouble(4,Double.parseDouble(amt.getText()));q.setString(5,note.getText());q.executeUpdate();loadParty(m,table,ledger,fk);}catch(Exception x){err(x);}});f.add(add);f.add(pay);p.add(f,BorderLayout.SOUTH);t.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting()&&t.getSelectedRow()>=0)ledgerDialog(table,ledger,fk,(Integer)m.getValueAt(t.getSelectedRow(),0));});return p;}
    void loadParty(DefaultTableModel m,String table,String ledger,String fk){m.setRowCount(0);try(Connection c=db();ResultSet r=c.createStatement().executeQuery("SELECT id,name,phone,email,address,opening_balance FROM "+table+" WHERE active=1 ORDER BY name")){while(r.next()){int id=r.getInt(1);double b=r.getDouble(6)+num(c,"SELECT COALESCE(SUM(CASE WHEN type LIKE 'PAYMENT%' THEN -amount ELSE amount END),0) FROM "+ledger+" WHERE "+fk+"="+id);m.addRow(new Object[]{id,r.getString(2),r.getString(3),r.getString(4),r.getString(5),money(r.getDouble(6)),money(b)});}}catch(Exception e){err(e);}}
    void ledgerDialog(String table,String ledger,String fk,int id){try(Connection c=db();PreparedStatement p=c.prepareStatement("SELECT at,type,amount,note FROM "+ledger+" WHERE "+fk+"=? ORDER BY id DESC")){p.setInt(1,id);StringBuilder b=new StringBuilder();try(ResultSet r=p.executeQuery()){while(r.next())b.append(r.getString(1)).append(" | ").append(r.getString(2)).append(" | ").append(money(r.getDouble(3))).append(" | ").append(r.getString(4)).append('\n');}JOptionPane.showMessageDialog(this,new JScrollPane(new JTextArea(b.toString(),20,80)),table+" History",JOptionPane.INFORMATION_MESSAGE);}catch(Exception e){err(e);}}
    void productHistory(int id){try(Connection c=db()){StringBuilder b=new StringBuilder("PRODUCT HISTORY\n");try(PreparedStatement p=c.prepareStatement("SELECT sold_at,receipt_no,total,status FROM sales WHERE id IN (SELECT sale_id FROM sale_items WHERE product_id=?) ORDER BY id DESC")){p.setInt(1,id);try(ResultSet r=p.executeQuery()){while(r.next())b.append(r.getString(1)).append(" | ").append(r.getString(2)).append(" | ").append(money(r.getDouble(3))).append(" | ").append(r.getString(4)).append('\n');}}JOptionPane.showMessageDialog(this,new JScrollPane(new JTextArea(b.toString(),18,80)),"Product History",JOptionPane.INFORMATION_MESSAGE);}catch(Exception e){err(e);}}
    JPanel expenses(){JPanel p=new JPanel(new BorderLayout());DefaultTableModel m=model("ID","Date","Category","Amount","Note","User");JTable t=new JTable(m);reloadExpenses(m);p.add(new JScrollPane(t));JTextField cat=new JTextField(10),amt=new JTextField(8),note=new JTextField(15);JButton b=new JButton("Add Expense");b.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO expenses(at,category,amount,note,user) VALUES(?,?,?,?,?)")){q.setString(1,now());q.setString(2,cat.getText());q.setDouble(3,Double.parseDouble(amt.getText()));q.setString(4,note.getText());q.setString(5,user);q.executeUpdate();reloadExpenses(m);}catch(Exception x){err(x);}});JPanel f=new JPanel(new FlowLayout());f.add(cat);f.add(amt);f.add(note);f.add(b);p.add(f,BorderLayout.SOUTH);return p;}
    void reloadExpenses(DefaultTableModel m){m.setRowCount(0);try(Connection c=db();ResultSet r=c.createStatement().executeQuery("SELECT id,at,category,amount,note,user FROM expenses ORDER BY id DESC")){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),money(r.getDouble(4)),r.getString(5),r.getString(6)});}catch(Exception e){err(e);}}
    JPanel cash(){JPanel p=new JPanel(new BorderLayout());JTextArea a=new JTextArea();a.setEditable(false);JPanel f=new JPanel(new FlowLayout());JTextField opening=new JTextField(8),amt=new JTextField(8),note=new JTextField(12);JButton open=new JButton("Open Day");open.addActionListener(e->openDay(opening.getText()));JButton ci=new JButton("Cash In");ci.addActionListener(e->cashTx("CASH_IN",amt.getText(),note.getText()));JButton co=new JButton("Cash Out");co.addActionListener(e->cashTx("CASH_OUT",amt.getText(),note.getText()));JButton close=new JButton("Close/Reconcile");close.addActionListener(e->closeDay(a));f.add(opening);f.add(open);f.add(amt);f.add(note);f.add(ci);f.add(co);f.add(close);p.add(f,BorderLayout.NORTH);p.add(a);refreshCash(a);return p;}
    String businessDate(){try(Connection c=db()){LocalTime t=LocalTime.parse(setting(c,"business_day_start","06:00"));LocalDate d=LocalDate.now();return LocalTime.now().isBefore(t)?d.minusDays(1).toString():d.toString();}catch(Exception e){return LocalDate.now().toString();}}
    void openDay(String s){try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO cash_sessions(business_date,opened_at,opening_cash,status,user) VALUES(?,?,?,?,?) ON CONFLICT(business_date) DO UPDATE SET opening_cash=excluded.opening_cash,status='OPEN'")){q.setString(1,businessDate());q.setString(2,now());q.setDouble(3,Double.parseDouble(s));q.setString(4,"OPEN");q.setString(5,user);q.executeUpdate();JOptionPane.showMessageDialog(this,"Business day opened: "+businessDate());}catch(Exception e){err(e);}}
    void cashTx(String type,String s,String n){try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO cash_transactions(at,type,amount,note,user) VALUES(?,?,?,?,?)")){q.setString(1,now());q.setString(2,type);q.setDouble(3,Double.parseDouble(s));q.setString(4,n);q.setString(5,user);q.executeUpdate();}catch(Exception e){err(e);}}
    void refreshCash(JTextArea a){try(Connection c=db()){double open=num(c,"SELECT COALESCE(opening_cash,0) FROM cash_sessions WHERE business_date='"+businessDate()+"'");double sales=num(c,"SELECT COALESCE(SUM(cash-change_amount),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')");double in=num(c,"SELECT COALESCE(SUM(amount),0) FROM cash_transactions WHERE type='CASH_IN' AND date(at)=date('now','localtime')");double out=num(c,"SELECT COALESCE(SUM(amount),0) FROM cash_transactions WHERE type='CASH_OUT' AND date(at)=date('now','localtime')");double exp=num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(at)=date('now','localtime')");a.setText("Business date: "+businessDate()+"\nOpening: "+money(open)+"\nNet cash sales: "+money(sales)+"\nCash in: "+money(in)+"\nCash out: "+money(out)+"\nExpenses: "+money(exp)+"\nExpected closing: "+money(open+sales+in-out-exp));}catch(Exception e){a.setText(e.getMessage());}}
    void closeDay(JTextArea a){String s=JOptionPane.showInputDialog(this,"Actual cash counted:");try(Connection c=db()){double actual=Double.parseDouble(s);double expected=num(c,"SELECT COALESCE(opening_cash,0) FROM cash_sessions WHERE business_date='"+businessDate()+"'")+num(c,"SELECT COALESCE(SUM(cash-change_amount),0) FROM sales WHERE status='COMPLETED' AND date(sold_at)=date('now','localtime')")+num(c,"SELECT COALESCE(SUM(CASE WHEN type='CASH_IN' THEN amount ELSE -amount END),0) FROM cash_transactions WHERE date(at)=date('now','localtime')")-num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses WHERE date(at)=date('now','localtime')");try(PreparedStatement q=c.prepareStatement("UPDATE cash_sessions SET closing_cash=?,closed_at=?,status='CLOSED' WHERE business_date=?")){q.setDouble(1,actual);q.setString(2,now());q.setString(3,businessDate());q.executeUpdate();}a.setText("Expected: "+money(expected)+"\nActual: "+money(actual)+"\nDifference: "+money(actual-expected));}catch(Exception e){err(e);}}
    JPanel reports(){JPanel p=new JPanel(new BorderLayout());JTextArea a=new JTextArea();a.setEditable(false);JButton b=new JButton("Calculate Profit/Loss & Cash Flow");b.addActionListener(e->report(a));p.add(b,BorderLayout.NORTH);p.add(new JScrollPane(a));report(a);return p;}
    void report(JTextArea a){try(Connection c=db()){double revenue=num(c,"SELECT COALESCE(SUM(total),0) FROM sales WHERE status='COMPLETED'")-num(c,"SELECT COALESCE(SUM(total),0) FROM sales WHERE status='REFUNDED'");double cogs=num(c,"SELECT COALESCE(SUM(si.qty*COALESCE(p.cost_price,0)),0) FROM sale_items si LEFT JOIN products p ON p.id=si.product_id JOIN sales s ON s.id=si.sale_id WHERE s.status='COMPLETED'");double exp=num(c,"SELECT COALESCE(SUM(amount),0) FROM expenses");double gross=revenue-cogs;double net=gross-exp;double flow=num(c,"SELECT COALESCE(SUM(CASE WHEN type='CASH_IN' THEN amount ELSE -amount END),0) FROM cash_transactions");a.setText("REVENUE: "+money(revenue)+"\nCOGS: "+money(cogs)+"\nGROSS PROFIT: "+money(gross)+"\nEXPENSES: "+money(exp)+"\nNET PROFIT / LOSS: "+money(net)+"\nOTHER CASH FLOW: "+money(flow));}catch(Exception e){a.setText(e.getMessage());}}
    JPanel printer(){JPanel p=new JPanel(new BorderLayout());JTextArea a=new JTextArea();JTextField mac=new JTextField(18);try(Connection c=db()){mac.setText(setting(c,"printer_bluetooth_mac",""));}catch(Exception ignored){}JButton save=new JButton("Save MAC / Auto-Reconnect");save.addActionListener(e->{try(Connection c=db()){set(c,"printer_bluetooth_mac",mac.getText());set(c,"printer_auto_reconnect","true");a.setText("Saved Bluetooth MAC: "+mac.getText()+"\n80mm profile enabled.\nAuto-reconnect preference is persisted.\nDirect Bluetooth ESC/POS connection remains OS/printer-driver dependent.");}catch(Exception x){err(x);}});JButton detect=new JButton("Detect Printers");detect.addActionListener(e->a.setText(Printer.detect()));JButton test=new JButton("Test Print");test.addActionListener(e->Printer.test());JPanel f=new JPanel(new FlowLayout());f.add(new JLabel("Bluetooth MAC"));f.add(mac);f.add(save);f.add(detect);f.add(test);p.add(f,BorderLayout.NORTH);p.add(new JScrollPane(a));return p;}
    JPanel settings(){JPanel p=new JPanel(new GridLayout(0,2,5,5));String[] k={"business_name","business_address","business_phone","currency","tax_rate","business_day_start","printer_bluetooth_mac","receipt_footer"};Map<String,JTextField> fs=new LinkedHashMap<>();try(Connection c=db()){for(String x:k){p.add(new JLabel(x));JTextField f=new JTextField(setting(c,x,""));fs.put(x,f);p.add(f);}}catch(Exception e){err(e);}JButton save=new JButton("SAVE SETTINGS");save.addActionListener(e->{try(Connection c=db()){for(Map.Entry<String,JTextField>x:fs.entrySet())set(c,x.getKey(),x.getValue().getText());JOptionPane.showMessageDialog(this,"Settings saved permanently.");}catch(Exception x){err(x);}});p.add(save);return p;}
    static final class Printer{static String detect(){try{String os=System.getProperty("os.name").toLowerCase();Process p=os.contains("win")?new ProcessBuilder("powershell","-NoProfile","-Command","Get-Printer | Select Name,PrinterStatus | Out-String").start():new ProcessBuilder("sh","-c","lpstat -p 2>/dev/null || lpstat -a 2>/dev/null").start();return new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);}catch(Exception e){return "Detection unavailable: "+e.getMessage();}}static void test(){try{new JTextArea("MK Pizza & Ice Bar\n80mm TEST RECEIPT\n"+now()+"\nThank you!\n").print();}catch(Exception e){JOptionPane.showMessageDialog(null,"Print failed: "+e.getMessage());}}}
    static void err(Exception e){JOptionPane.showMessageDialog(null,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);}
}
