package com.findupto.fastfood;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.print.PrinterJob;
import java.sql.*;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** MK Pizza & Ice Bar POS. Java 17 + Swing + SQLite. */
public class FastfoodPOS extends JFrame {
    private static final String DB = "jdbc:sqlite:fastfood.db";
    private static final String CURRENCY = "Rs.";
    private static final double TAX_RATE = 0.0;
    private static final NumberFormat MONEY = NumberFormat.getNumberInstance(Locale.US);
    private static final DateTimeFormatter DT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private static final String BUSINESS = "MK Pizza & Ice Bar";
    private static final String ADDRESS = "Collage Road Abbas Chowk, Bhakkar, Pakistan";
    private static final String PHONE = "0316 9700025";
    private final String username, role;
    private final List<CartLine> cart = new ArrayList<>();
    private final DefaultTableModel cartModel = model("Item", "Qty", "Price", "Amount");
    private final JTable cartTable = new JTable(cartModel);
    private final JLabel subtotalLabel=new JLabel(), taxLabel=new JLabel(), discountLabel=new JLabel(), totalLabel=new JLabel();
    private final JTextField discountField=new JTextField("0",5), cashField=new JTextField(8);
    private final JTextArea receiptArea=new JTextArea(); private final JLabel status=new JLabel(" Ready");
    record Product(int id,String code,String name,String category,double price,int stock) {}
    record CartLine(Product product,int qty) {}
    public FastfoodPOS(String username,String role){this.username=username;this.role=role;setTitle(BUSINESS+" - POS - "+username);setDefaultCloseOperation(EXIT_ON_CLOSE);setMinimumSize(new Dimension(1250,780));setLocationRelativeTo(null);buildUi();refreshTotals();}
    private static DefaultTableModel model(String... c){return new DefaultTableModel(c,0){public boolean isCellEditable(int r,int c){return false;}};}
    private static String money(double v){return CURRENCY+" "+MONEY.format(v);} private static Connection db()throws SQLException{return DriverManager.getConnection(DB);}
    private static void initDb(){try(Connection c=db();Statement s=c.createStatement()){
        s.execute("PRAGMA foreign_keys=ON");s.executeUpdate("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,price REAL NOT NULL,stock INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,receipt_no TEXT UNIQUE NOT NULL,sold_at TEXT NOT NULL,total REAL NOT NULL,discount REAL NOT NULL,tax REAL NOT NULL,cash REAL NOT NULL,change_amount REAL NOT NULL,payment TEXT NOT NULL,cashier TEXT NOT NULL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS sale_items(id INTEGER PRIMARY KEY AUTOINCREMENT,sale_id INTEGER NOT NULL REFERENCES sales(id),product_id INTEGER,product_name TEXT NOT NULL,qty INTEGER NOT NULL,price REAL NOT NULL,amount REAL NOT NULL)");
        s.executeUpdate("CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL)");upsertUser(c,"admin","0099","ADMIN");upsertUser(c,"owner","0099","OWNER");
        setDefault(c,"business_name",BUSINESS);setDefault(c,"business_address",ADDRESS);setDefault(c,"business_phone",PHONE);setDefault(c,"currency",CURRENCY);setDefault(c,"tax_rate","0");setDefault(c,"printer_bluetooth_mac","");setDefault(c,"receipt_footer","Thank you! Visit again.");
        Object[][] seed={{"B01","Zinger Burger","Burgers",450,50},{"B02","Chicken Burger","Burgers",380,50},{"B03","Beef Burger","Burgers",520,30},{"F01","Chicken Fries","Fries",300,60},{"F02","Loaded Fries","Fries",420,40},{"P01","Chicken Pizza","Pizza",850,25},{"P02","Pepperoni Pizza","Pizza",950,25},{"D01","Cold Drink","Drinks",120,100},{"D02","Fresh Lemonade","Drinks",180,80},{"D03","Mineral Water","Drinks",80,100}};
        try(PreparedStatement p=c.prepareStatement("INSERT OR IGNORE INTO products(code,name,category,price,stock) VALUES(?,?,?,?,?)")){for(Object[] x:seed){for(int i=0;i<x.length;i++)p.setObject(i+1,x[i]);p.addBatch();}p.executeBatch();}
    }catch(SQLException e){throw new RuntimeException("Database initialization failed: "+e.getMessage(),e);}}
    private static void upsertUser(Connection c,String u,String p,String r)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT INTO users(username,password,role) VALUES(?,?,?) ON CONFLICT(username) DO UPDATE SET password=excluded.password,role=excluded.role")){q.setString(1,u);q.setString(2,p);q.setString(3,r);q.executeUpdate();}}
    private static void setDefault(Connection c,String k,String v)throws SQLException{try(PreparedStatement q=c.prepareStatement("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)")){q.setString(1,k);q.setString(2,v);q.executeUpdate();}}
    private static String setting(String k,String f){try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT value FROM settings WHERE key=?")){q.setString(1,k);try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):f;}}catch(SQLException e){return f;}}
    private static boolean login(String u,String p){try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT 1 FROM users WHERE username=? AND password=?")){q.setString(1,u);q.setString(2,p);try(ResultSet r=q.executeQuery()){return r.next();}}catch(SQLException e){return false;}}
    private static String userRole(String u){try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT role FROM users WHERE username=?")){q.setString(1,u);try(ResultSet r=q.executeQuery()){return r.next()?r.getString(1):"";}}catch(SQLException e){return "";}}
    private static List<Product> products(){List<Product> out=new ArrayList<>();try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT id,code,name,category,price,stock FROM products WHERE active=1 ORDER BY category,name");ResultSet r=q.executeQuery()){while(r.next())out.add(new Product(r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getDouble(5),r.getInt(6)));}catch(SQLException e){error(e.getMessage());}return out;}
    private void buildUi(){JPanel root=new JPanel(new BorderLayout(10,10));root.setBorder(new EmptyBorder(10,10,10,10));JLabel title=new JLabel(BUSINESS);title.setFont(new Font("SansSerif",Font.BOLD,26));JPanel h=new JPanel(new BorderLayout());h.add(title,BorderLayout.WEST);h.add(new JLabel("User: "+username+" | Role: "+role),BorderLayout.EAST);root.add(h,BorderLayout.NORTH);JTabbedPane tabs=new JTabbedPane();tabs.addTab("POS",posPanel());tabs.addTab("Products & Stock",productsPanel());tabs.addTab("Reports",reportsPanel());if(role.equals("ADMIN")||role.equals("OWNER"))tabs.addTab("Settings",settingsPanel());root.add(tabs,BorderLayout.CENTER);status.setBorder(BorderFactory.createEtchedBorder());root.add(status,BorderLayout.SOUTH);setContentPane(root);}
    private JPanel posPanel(){JPanel p=new JPanel(new BorderLayout(8,8));JPanel menu=new JPanel(new GridLayout(0,3,6,6));menu.setBorder(BorderFactory.createTitledBorder("Menu"));for(Product x:products()){JButton b=new JButton("<html><b>"+x.name()+"</b><br>"+money(x.price())+"<br>Stock: "+x.stock()+"</html>");b.setEnabled(x.stock()>0);b.addActionListener(e->add(x));menu.add(b);}p.add(new JScrollPane(menu),BorderLayout.CENTER);JPanel right=new JPanel(new BorderLayout(6,6));right.setPreferredSize(new Dimension(500,620));right.add(new JScrollPane(cartTable),BorderLayout.CENTER);cartTable.setRowHeight(28);JPanel controls=new JPanel(new GridLayout(0,2,5,5));controls.add(new JLabel("Discount %"));controls.add(discountField);controls.add(new JLabel("Cash Received"));controls.add(cashField);controls.add(new JLabel("Subtotal"));controls.add(subtotalLabel);controls.add(new JLabel("Tax (0%)"));controls.add(taxLabel);controls.add(new JLabel("Discount"));controls.add(discountLabel);controls.add(new JLabel("TOTAL"));controls.add(totalLabel);JButton remove=new JButton("Remove");remove.addActionListener(e->{int r=cartTable.getSelectedRow();if(r>=0){cart.remove(r);refreshCart();}});JButton clear=new JButton("Clear");clear.addActionListener(e->{cart.clear();refreshCart();});JButton print=new JButton("Print Receipt");print.addActionListener(e->printReceipt());JButton checkout=new JButton("CHECKOUT / SAVE SALE");checkout.addActionListener(e->checkout());JPanel a=new JPanel(new GridLayout(1,4,5,5));a.add(remove);a.add(clear);a.add(print);a.add(checkout);controls.add(a);controls.add(new JLabel());right.add(controls,BorderLayout.SOUTH);p.add(right,BorderLayout.EAST);return p;}
    private JPanel productsPanel(){JPanel p=new JPanel(new BorderLayout(8,8));DefaultTableModel m=model("ID","Code","Name","Category","Price","Stock");JTable t=new JTable(m);refreshProductTable(m);p.add(new JScrollPane(t),BorderLayout.CENTER);JPanel f=new JPanel(new FlowLayout(FlowLayout.LEFT));JTextField code=new JTextField(6),name=new JTextField(14),cat=new JTextField(10),price=new JTextField(7),stock=new JTextField(5);f.add(new JLabel("Code"));f.add(code);f.add(new JLabel("Name"));f.add(name);f.add(new JLabel("Category"));f.add(cat);f.add(new JLabel("Price"));f.add(price);f.add(new JLabel("Stock"));f.add(stock);JButton save=new JButton("Add / Update");save.addActionListener(e->{try{saveProduct(m,code,name,cat,price,stock);}catch(Exception ex){error("Invalid product data: "+ex.getMessage());}});JButton del=new JButton("Deactivate Selected");del.addActionListener(e->{int r=t.getSelectedRow();if(r>=0)try(Connection c=db();PreparedStatement q=c.prepareStatement("UPDATE products SET active=0 WHERE id=?")){q.setInt(1,(int)m.getValueAt(r,0));q.executeUpdate();refreshProductTable(m);}catch(SQLException ex){error(ex.getMessage());}});f.add(save);f.add(del);p.add(f,BorderLayout.SOUTH);return p;}
    private void refreshProductTable(DefaultTableModel m){m.setRowCount(0);for(Product x:products())m.addRow(new Object[]{x.id(),x.code(),x.name(),x.category(),money(x.price()),x.stock()});}
    private void saveProduct(DefaultTableModel m,JTextField code,JTextField name,JTextField cat,JTextField price,JTextField stock)throws SQLException{if(code.getText().isBlank()||name.getText().isBlank()||cat.getText().isBlank())throw new IllegalArgumentException("Code, name and category are required");try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO products(code,name,category,price,stock) VALUES(?,?,?,?,?) ON CONFLICT(code) DO UPDATE SET name=excluded.name,category=excluded.category,price=excluded.price,stock=excluded.stock")){q.setString(1,code.getText().trim());q.setString(2,name.getText().trim());q.setString(3,cat.getText().trim());q.setDouble(4,Double.parseDouble(price.getText()));q.setInt(5,Integer.parseInt(stock.getText()));q.executeUpdate();}refreshProductTable(m);status.setText(" Product saved");}
    private JPanel reportsPanel(){JPanel p=new JPanel(new BorderLayout(8,8));JTextArea out=new JTextArea();out.setEditable(false);out.setFont(new Font(Font.MONOSPACED,Font.PLAIN,13));JButton refresh=new JButton("Refresh Dashboard");refresh.addActionListener(e->out.setText(report()));p.add(refresh,BorderLayout.NORTH);p.add(new JScrollPane(out),BorderLayout.CENTER);out.setText(report());return p;}
    private String report(){StringBuilder b=new StringBuilder(BUSINESS+"\nSALES DASHBOARD\n=========================\n\n");try(Connection c=db();Statement s=c.createStatement()){try(ResultSet r=s.executeQuery("SELECT COUNT(*),COALESCE(SUM(total),0),COALESCE(AVG(total),0) FROM sales WHERE date(sold_at)=date('now','localtime')")){if(r.next())b.append("Today Orders : ").append(r.getInt(1)).append("\nToday Sales  : ").append(money(r.getDouble(2))).append("\nAvg Order    : ").append(money(r.getDouble(3))).append("\n\n");}b.append("RECENT SALES\n");try(ResultSet r=s.executeQuery("SELECT receipt_no,sold_at,total,payment,cashier FROM sales ORDER BY id DESC LIMIT 20")){while(r.next())b.append(String.format("%-18s %-19s %12s %-8s %s%n",r.getString(1),r.getString(2),money(r.getDouble(3)),r.getString(4),r.getString(5)));}b.append("\nTOP SELLING ITEMS\n");try(ResultSet r=s.executeQuery("SELECT product_name,SUM(qty) qty FROM sale_items GROUP BY product_id ORDER BY qty DESC LIMIT 10")){while(r.next())b.append(String.format("%-28s %5d%n",r.getString(1),r.getInt(2)));}b.append("\nLOW STOCK (<=10)\n");try(ResultSet r=s.executeQuery("SELECT code,name,stock FROM products WHERE active=1 AND stock<=10 ORDER BY stock")){while(r.next())b.append(String.format("%-6s %-28s %5d%n",r.getString(1),r.getString(2),r.getInt(3)));}}catch(SQLException e){b.append("Database error: ").append(e.getMessage());}return b.toString();}
    private JPanel settingsPanel(){JPanel p=new JPanel(new GridBagLayout());GridBagConstraints g=new GridBagConstraints();g.insets=new Insets(8,8,8,8);g.anchor=GridBagConstraints.WEST;g.fill=GridBagConstraints.HORIZONTAL;String[] labels={"Business Name","Address","Phone","Currency","Tax %","Bluetooth Printer MAC","Receipt Footer"};JTextField[] f={new JTextField(setting("business_name",BUSINESS),28),new JTextField(setting("business_address",ADDRESS),28),new JTextField(setting("business_phone",PHONE),18),new JTextField(setting("currency",CURRENCY),8),new JTextField(setting("tax_rate","0"),8),new JTextField(setting("printer_bluetooth_mac",""),20),new JTextField(setting("receipt_footer","Thank you! Visit again."),28)};for(int i=0;i<labels.length;i++){g.gridx=0;g.gridy=i;p.add(new JLabel(labels[i]),g);g.gridx=1;p.add(f[i],g);}g.gridx=0;g.gridy=7;g.gridwidth=2;p.add(new JLabel("Bluetooth MAC is stored for configuration; Java printing uses the selected system printer."),g);JButton save=new JButton("Save Settings");save.addActionListener(e->{try(Connection c=db();PreparedStatement q=c.prepareStatement("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value")){String[][] v={{"business_name",f[0].getText()},{"business_address",f[1].getText()},{"business_phone",f[2].getText()},{"currency",f[3].getText()},{"tax_rate",f[4].getText()},{"printer_bluetooth_mac",f[5].getText()},{"receipt_footer",f[6].getText()}};for(String[] x:v){q.setString(1,x[0]);q.setString(2,x[1]);q.addBatch();}q.executeBatch();status.setText(" Settings saved");}catch(SQLException ex){error(ex.getMessage());}});g.gridy=8;p.add(save,g);return p;}
    private void add(Product p){for(CartLine x:cart)if(x.product.id()==p.id()){if(x.qty()>=p.stock()){error("Not enough stock.");return;}cart.set(cart.indexOf(x),new CartLine(x.product(),x.qty()+1));refreshCart();return;}cart.add(new CartLine(p,1));refreshCart();}
    private void refreshCart(){cartModel.setRowCount(0);for(CartLine x:cart)cartModel.addRow(new Object[]{x.product.name(),x.qty(),money(x.product.price()),money(x.product.price()*x.qty())});refreshTotals();}
    private double subtotal(){return cart.stream().mapToDouble(x->x.product.price()*x.qty()).sum();}private double discountAmount(){try{return Math.max(0,Math.min(100,Double.parseDouble(discountField.getText())))*subtotal()/100;}catch(Exception e){return 0;}}private double taxAmount(){return (subtotal()-discountAmount())*TAX_RATE;}private double total(){return subtotal()-discountAmount()+taxAmount();}
    private void refreshTotals(){subtotalLabel.setText(money(subtotal()));taxLabel.setText(money(taxAmount()));discountLabel.setText(money(discountAmount()));totalLabel.setText(money(total()));totalLabel.setFont(totalLabel.getFont().deriveFont(Font.BOLD,16f));}
    private void checkout(){if(cart.isEmpty()){error("Order is empty.");return;}double cash;try{cash=Double.parseDouble(cashField.getText());}catch(Exception e){error("Enter valid cash received.");return;}if(cash<total()){error("Insufficient cash. Required: "+money(total()));return;}double sub=subtotal(),disc=discountAmount(),tax=taxAmount(),tot=total(),change=cash-tot;String no="FF-"+System.currentTimeMillis();try(Connection c=db()){c.setAutoCommit(false);try(PreparedStatement sale=c.prepareStatement("INSERT INTO sales(receipt_no,sold_at,total,discount,tax,cash,change_amount,payment,cashier) VALUES(?,?,?,?,?,?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){sale.setString(1,no);sale.setString(2,LocalDateTime.now().format(DT));sale.setDouble(3,tot);sale.setDouble(4,disc);sale.setDouble(5,tax);sale.setDouble(6,cash);sale.setDouble(7,change);sale.setString(8,"CASH");sale.setString(9,username);sale.executeUpdate();int saleId;try(ResultSet k=sale.getGeneratedKeys()){if(!k.next())throw new SQLException("Could not create sale ID");saleId=k.getInt(1);}try(PreparedStatement item=c.prepareStatement("INSERT INTO sale_items(sale_id,product_id,product_name,qty,price,amount) VALUES(?,?,?,?,?,?)");PreparedStatement stock=c.prepareStatement("UPDATE products SET stock=stock-? WHERE id=? AND stock>=?")){for(CartLine x:cart){stock.setInt(1,x.qty());stock.setInt(2,x.product.id());stock.setInt(3,x.qty());if(stock.executeUpdate()!=1)throw new SQLException("Stock changed for "+x.product.name());item.setInt(1,saleId);item.setInt(2,x.product.id());item.setString(3,x.product.name());item.setInt(4,x.qty());item.setDouble(5,x.product.price());item.setDouble(6,x.product.price()*x.qty());item.addBatch();}item.executeBatch();}c.commit();}catch(Exception e){c.rollback();throw e;}}catch(Exception e){error("Could not save sale: "+e.getMessage());return;}receiptArea.setText(buildReceipt(no,cash,change));cart.clear();cashField.setText("");discountField.setText("0");refreshCart();status.setText(" Sale saved: "+no);JOptionPane.showMessageDialog(this,"Sale completed\nReceipt: "+no,"Success",JOptionPane.INFORMATION_MESSAGE);}
    private String buildReceipt(String no,double cash,double change){StringBuilder b=new StringBuilder();b.append("========================================\n").append(setting("business_name",BUSINESS)).append("\n").append(setting("business_address",ADDRESS)).append("\nPhone: ").append(setting("business_phone",PHONE)).append("\nReceipt: ").append(no).append("\n").append(LocalDateTime.now().format(DT)).append("\nCashier: ").append(username).append("\n========================================\n");for(CartLine x:cart)b.append(String.format("%-22s %2dx %12s%n",x.product.name(),x.qty(),money(x.product.price()*x.qty())));b.append("----------------------------------------\n");b.append(String.format("%-25s %12s%n","Subtotal",money(subtotal())));b.append(String.format("%-25s %12s%n","Discount",money(discountAmount())));b.append(String.format("%-25s %12s%n","Tax",money(taxAmount())));b.append(String.format("%-25s %12s%n","TOTAL",money(total())));b.append(String.format("%-25s %12s%n","Cash",money(cash)));b.append(String.format("%-25s %12s%n","Change",money(change)));b.append("========================================\n").append(setting("receipt_footer","Thank you! Visit again.")).append("\n========================================\n");return b.toString();}
    private void printReceipt(){if(receiptArea.getText().isBlank()){error("Complete checkout first.");return;}try{PrinterJob job=PrinterJob.getPrinterJob();if(job.printDialog()){job.setPrintable((graphics,pageFormat,pageIndex)->{if(pageIndex>0)return java.awt.print.Printable.NO_SUCH_PAGE;Graphics2D g=(Graphics2D)graphics;g.setFont(new Font(Font.MONOSPACED,Font.PLAIN,9));int y=40;for(String line:receiptArea.getText().split("\\n")){g.drawString(line,30,y);y+=12;}return java.awt.print.Printable.PAGE_EXISTS;});job.print();}}catch(Exception e){error("Printing failed: "+e.getMessage());}}
    private static void error(String m){JOptionPane.showMessageDialog(null,m,"POS",JOptionPane.WARNING_MESSAGE);}
    public static void main(String[] args){initDb();SwingUtilities.invokeLater(()->{try{UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());}catch(Exception ignored){}JPanel login=new JPanel(new GridLayout(2,2,8,8));JTextField u=new JTextField("admin");JPasswordField p=new JPasswordField();login.add(new JLabel("Username"));login.add(u);login.add(new JLabel("Password"));login.add(p);while(true){int r=JOptionPane.showConfirmDialog(null,login,"MK Pizza & Ice Bar - Login",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);if(r!=JOptionPane.OK_OPTION)System.exit(0);if(login(u.getText().trim(),new String(p.getPassword()))){new FastfoodPOS(u.getText().trim(),userRole(u.getText().trim())).setVisible(true);break;}JOptionPane.showMessageDialog(null,"Invalid username or password.","Login Failed",JOptionPane.ERROR_MESSAGE);p.setText("");}});}
}
