package com.findupto.fastfood;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.*;

/** Supplier purchase and stock-in module. */
public final class PurchasesPanel extends JPanel {
    static final String DB="jdbc:sqlite:fastfood.db"; final String user; final DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Date","Supplier","Product","Qty","Cost","Total"},0);
    public PurchasesPanel(String u){user=u;setLayout(new BorderLayout());JTable t=new JTable(m);load();add(new JScrollPane(t));JPanel f=new JPanel(new FlowLayout());JTextField supplier=new JTextField(10),code=new JTextField(7),qty=new JTextField(6),cost=new JTextField(7),paid=new JTextField(7);JButton add=new JButton("Purchase / Stock In");add.addActionListener(e->purchase(supplier.getText(),code.getText(),qty.getText(),cost.getText(),paid.getText()));f.add(new JLabel("Supplier"));f.add(supplier);f.add(new JLabel("Product Code"));f.add(code);f.add(new JLabel("Qty"));f.add(qty);f.add(new JLabel("Cost"));f.add(cost);f.add(new JLabel("Paid"));f.add(paid);f.add(add);add(f,BorderLayout.SOUTH);}
    Connection db()throws SQLException{return DriverManager.getConnection(DB);}
    void purchase(String supplier,String code,String qs,String cs,String ps){try(Connection c=db()){c.setAutoCommit(false);int pid;try(PreparedStatement q=c.prepareStatement("SELECT id FROM products WHERE code=? AND active=1")){q.setString(1,code);try(ResultSet r=q.executeQuery()){if(!r.next())throw new SQLException("Product code not found");pid=r.getInt(1);}}int qty=Integer.parseInt(qs);double unit=Double.parseDouble(cs),paid=Double.parseDouble(ps.isBlank()?"0":ps),total=qty*unit;int sid=0;try(PreparedStatement q=c.prepareStatement("SELECT id FROM suppliers WHERE name=? AND active=1 LIMIT 1")){q.setString(1,supplier);try(ResultSet r=q.executeQuery()){if(r.next())sid=r.getInt(1);}}try(PreparedStatement q=c.prepareStatement("INSERT INTO stock_movements(product_id,at,type,qty,cost,note,user) VALUES(?,?,?,?,?,?,?)")){q.setInt(1,pid);q.setString(2,java.time.LocalDateTime.now().toString());q.setString(3,"PURCHASE");q.setInt(4,qty);q.setDouble(5,unit);q.setString(6,"Supplier: "+supplier);q.setString(7,user);q.executeUpdate();}try(PreparedStatement q=c.prepareStatement("UPDATE products SET stock=stock+?,cost_price=? WHERE id=?")){q.setInt(1,qty);q.setDouble(2,unit);q.setInt(3,pid);q.executeUpdate();}if(sid>0&&total-paid!=0)try(PreparedStatement q=c.prepareStatement("INSERT INTO supplier_ledger(supplier_id,at,type,amount,note) VALUES(?,?,?,?,?)")){q.setInt(1,sid);q.setString(2,java.time.LocalDateTime.now().toString());q.setString(3,"PURCHASE");q.setDouble(4,total-paid);q.setString(5,"Product "+code+" qty "+qty);q.executeUpdate();}c.commit();load();JOptionPane.showMessageDialog(this,"Purchase saved and stock updated.");}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
    void load(){m.setRowCount(0);try(Connection c=db();ResultSet r=c.createStatement().executeQuery("SELECT sm.id,sm.at,COALESCE(sm.note,''),p.name,sm.qty,sm.cost,sm.qty*sm.cost FROM stock_movements sm LEFT JOIN products p ON p.id=sm.product_id WHERE sm.type='PURCHASE' ORDER BY sm.id DESC")){while(r.next())m.addRow(new Object[]{r.getInt(1),r.getString(2),r.getString(3),r.getString(4),r.getInt(5),r.getDouble(6),r.getDouble(7)});}catch(Exception ignored){}}
}
